#spring:  
#  datasource:  
#    url : jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false  
#    username : root  
#    password : x  
#    driver-class-name : com.mysql.jdbc.Driver  
#  jpa:  
#    show-sql : true  
#server:
#    context-path:/sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /tmp/
#  file: /tmp/sell.log/
#  level:
#    com:
#      xujie:
#        logdemo: debug


